import { useState } from 'react'
import useCertifyStore from '../store/certifyStore'

function CopyButton({ text, label = 'COPY' }) {
  const [copied, setCopied] = useState(false)
  const { addToast } = useCertifyStore()

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      addToast(`${label} copied!`, 'success')
      setTimeout(() => setCopied(false), 2000)
    } catch {
      addToast('Copy failed — please copy manually', 'error')
    }
  }

  return (
    <button
      onClick={handleCopy}
      className={`border-2 h-9 px-3 text-xs font-bold uppercase tracking-widest transition-all duration-200 flex-shrink-0 ${
        copied
          ? 'bg-accent text-accent-foreground border-accent'
          : 'border-border text-muted-foreground hover:bg-accent hover:text-accent-foreground hover:border-accent'
      }`}
    >
      {copied ? 'COPIED ✓' : '📋 ' + label}
    </button>
  )
}

function CollapsiblePhase({ phase }) {
  const [open, setOpen] = useState(false)
  return (
    <div className="border-2 border-border">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex justify-between items-center px-4 py-3 hover:bg-muted/50 transition-colors"
      >
        <span className="text-base font-bold uppercase tracking-wider text-foreground">{phase.phase}</span>
        <div className="flex items-center gap-3">
          <span className="bg-accent text-accent-foreground px-3 py-1 text-xs font-bold uppercase">
            {phase.events?.length || 0} EVENTS
          </span>
          <span className="text-muted-foreground">{open ? '−' : '+'}</span>
        </div>
      </button>
      {open && (
        <div className="border-t border-border px-4 py-4 bg-muted/20">
          {phase.mitreIds?.length > 0 && (
            <div className="flex gap-2 flex-wrap mb-3">
              {phase.mitreIds.map(id => (
                <span key={id} className="font-mono text-xs text-accent bg-accent/10 border border-accent/30 px-2 py-0.5">
                  {id}
                </span>
              ))}
            </div>
          )}
          <ul className="space-y-1">
            {phase.events?.map((evt, i) => (
              <li key={i} className="text-sm text-foreground leading-relaxed">
                <span className="text-muted-foreground text-xs mr-2">{i + 1}.</span>{evt}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  )
}

export default function CERTInEvidence() {
  const {
    certInEvidence, isGeneratingEvidence,
    generateCERTInEvidenceAction, layer2JsonSummary,
    apiKey, addToast,
  } = useCertifyStore()

  const hasEnvKey = Boolean(import.meta.env.VITE_GROQ_API_KEY);

  const copyAll = async () => {
    if (!certInEvidence) return
    const text = `CERT-In Incident Evidence Report
Generated by CERTify

=== INCIDENT TIMELINE ===
${certInEvidence.timeline}

=== ATTACK PHASES ===
${(certInEvidence.attackPhases || []).map(p => `${p.phase}:\n${(p.events || []).join('\n')}`).join('\n\n')}

=== AFFECTED SYSTEMS ===
${(certInEvidence.affectedSystems || []).join('\n')}

=== THREAT ACTOR ASSESSMENT ===
${certInEvidence.threatActorAssessment}

=== INDICATORS OF COMPROMISE ===
Source IPs: ${(certInEvidence.iocs?.sourceIPs || []).join(', ')}
User-Agents: ${(certInEvidence.iocs?.userAgents || []).join(', ')}
Payload Patterns: ${(certInEvidence.iocs?.payloadPatterns || []).join(', ')}

=== CERT-IN CATEGORY ===
${certInEvidence.certInCategory}

=== CERT-IN PORTAL FIELDS ===
Brief Description: ${certInEvidence.certInFields?.briefDescription}

How Detected: ${certInEvidence.certInFields?.howDetected}

Impact: ${certInEvidence.certInFields?.impact}

Actions Taken: ${certInEvidence.certInFields?.actionsTaken}
`
    try {
      await navigator.clipboard.writeText(text)
      addToast('Full evidence report copied!', 'success')
    } catch {
      addToast('Copy failed — please copy manually', 'error')
    }
  }

  const sectionLabel = (text) => (
    <p className="text-xs uppercase tracking-widest text-accent font-bold border-b-2 border-border pb-2 mb-4">
      {text}
    </p>
  )

  const certCategory = certInEvidence?.certInCategory || ''
  const categoryStyle =
    certCategory.toLowerCase().includes('unauthorised') || certCategory.toLowerCase().includes('unauthorized')
      ? 'border-accent bg-accent/10 text-accent'
      : certCategory.toLowerCase().includes('denial') || certCategory.toLowerCase().includes('ddos')
      ? 'border-severity-critical bg-severity-critical/10 text-severity-critical'
      : 'border-severity-high bg-severity-high/10 text-severity-high'

  return (
    <div className="px-6 md:px-12 py-10 min-h-[calc(100vh-130px)]">
      {/* Header */}
      <div className="mb-10 flex justify-between items-end flex-wrap gap-4">
        <div>
          <h2 className="text-2xl md:text-4xl font-bold uppercase tracking-tighter">
            <span className="text-accent">CERT-IN</span> EVIDENCE
          </h2>
          <p className="text-muted-foreground text-sm mt-1">
            Structured output for CERT-In portal submission
          </p>
        </div>
        {certInEvidence && (
          <button
            onClick={copyAll}
            className="border-2 border-border h-12 px-6 text-sm font-bold uppercase tracking-widest text-foreground hover:bg-foreground hover:text-background transition-all duration-200"
          >
            COPY ALL AS TEXT
          </button>
        )}
      </div>

      {/* Empty state */}
      {!certInEvidence && !isGeneratingEvidence && (
        <div className="flex flex-col items-center justify-center py-20 text-center">
          <div className="text-[6rem] md:text-[10rem] font-bold text-muted leading-none select-none mb-8" aria-hidden="true">§</div>
          <p className="text-xl text-muted-foreground max-w-2xl leading-relaxed mb-2">
            CERT-In requires organizations to submit a structured incident report within 6 hours of detection.
          </p>
          <p className="text-base text-muted-foreground max-w-2xl leading-relaxed mb-10">
            This tool generates copy-ready fields for all mandatory portal fields — incident timeline, IOCs, affected systems, and more.
          </p>
          <button
            onClick={generateCERTInEvidenceAction}
            disabled={!layer2JsonSummary || (!apiKey && !hasEnvKey)}
            className="bg-accent text-accent-foreground h-16 px-12 text-xl font-bold uppercase tracking-tighter hover:scale-[1.02] active:scale-95 transition-all duration-200 disabled:opacity-40 disabled:pointer-events-none"
          >
            ⚡ GENERATE CERT-IN EVIDENCE
          </button>
          {!apiKey && !hasEnvKey && (
            <div className="mt-6 flex items-center gap-2 text-severity-high bg-severity-high/10 px-4 py-2 border border-severity-high/30">
              <span className="text-xs font-bold uppercase tracking-widest">AI Config Missing</span>
              <span className="text-[0.6rem] uppercase tracking-tighter opacity-70">Set API key in top-right settings to enable</span>
            </div>
          )}
        </div>
      )}

      {/* Loading state */}
      {isGeneratingEvidence && (
        <div className="flex flex-col items-center justify-center py-20 text-center relative overflow-hidden">
          <div className="absolute inset-0 flex items-center justify-center pointer-events-none" aria-hidden="true">
            <span className="text-[12rem] font-bold text-muted leading-none animate-spin-slow opacity-10">⟳</span>
          </div>
          <div className="relative z-10">
            <h3 className="text-2xl md:text-4xl font-bold uppercase tracking-tighter text-accent mb-6">
              GENERATING CERT-IN EVIDENCE...
            </h3>
            <div className="flex gap-3 justify-center">
              {[0, 1, 2].map(i => (
                <div
                  key={i}
                  className="w-3 h-3 bg-accent"
                  style={{ animation: `pulse 1s ease-in-out ${i * 0.2}s infinite` }}
                />
              ))}
            </div>
            <p className="text-muted-foreground text-sm uppercase tracking-widest mt-4">
              Groq is analyzing your threat data...
            </p>
          </div>
        </div>
      )}

      {/* Evidence display */}
      {certInEvidence && !isGeneratingEvidence && (
        <div className="space-y-8">
          {/* 1. Incident Timeline */}
          <div>
            {sectionLabel('1. Incident Timeline')}
            <div className="bg-muted/30 border-2 border-border p-6 max-h-96 overflow-y-auto">
              <pre className="font-mono text-sm text-foreground leading-relaxed whitespace-pre-wrap">
                {certInEvidence.timeline}
              </pre>
            </div>
          </div>

          {/* 2. Attack Phases */}
          {certInEvidence.attackPhases?.length > 0 && (
            <div>
              {sectionLabel('2. Attack Phases (MITRE ATT&CK)')}
              <div className="space-y-2">
                {certInEvidence.attackPhases.map((phase, i) => (
                  <CollapsiblePhase key={i} phase={phase} />
                ))}
              </div>
            </div>
          )}

          {/* 3. Affected Systems */}
          {certInEvidence.affectedSystems?.length > 0 && (
            <div>
              {sectionLabel('3. Affected Systems')}
              <div className="flex flex-wrap gap-2">
                {certInEvidence.affectedSystems.map((sys, i) => (
                  <span
                    key={i}
                    className="border-2 border-border px-4 py-2 font-mono text-sm text-foreground hover:bg-accent hover:text-accent-foreground hover:border-accent transition-all duration-200 cursor-default"
                  >
                    {sys}
                  </span>
                ))}
              </div>
            </div>
          )}

          {/* 4. Threat Actor Assessment */}
          {certInEvidence.threatActorAssessment && (
            <div>
              {sectionLabel('4. Threat Actor Assessment')}
              <div className="border-l-4 border-l-accent bg-muted/20 p-6">
                <p className="text-base text-foreground leading-relaxed">{certInEvidence.threatActorAssessment}</p>
              </div>
            </div>
          )}

          {/* 5. IOCs */}
          {certInEvidence.iocs && (
            <div>
              {sectionLabel('5. Indicators of Compromise (IOCs)')}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-px bg-border">
                {[
                  { label: 'SOURCE IPs', items: certInEvidence.iocs.sourceIPs, critical: false },
                  { label: 'USER-AGENTS', items: certInEvidence.iocs.userAgents, critical: false },
                  { label: 'PAYLOAD PATTERNS', items: certInEvidence.iocs.payloadPatterns, critical: true },
                ].map(({ label, items, critical }) => (
                  <div key={label} className="bg-background p-6">
                    <p className="text-xs tracking-widest uppercase text-muted-foreground mb-3 font-bold">{label}</p>
                    <div className="max-h-48 overflow-y-auto space-y-1">
                      {(items || []).map((item, i) => (
                        <p key={i} className={`font-mono text-xs break-all leading-relaxed ${critical ? 'text-severity-critical' : 'text-foreground'}`}>
                          {item}
                        </p>
                      ))}
                      {(!items || items.length === 0) && (
                        <p className="text-muted-foreground text-xs">None detected</p>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* 6. CERT-In Category */}
          {certInEvidence.certInCategory && (
            <div>
              {sectionLabel('6. CERT-In Classification')}
              <div className={`inline-block border-2 px-6 py-4 text-xl font-bold uppercase tracking-wider ${categoryStyle}`}>
                {certInEvidence.certInCategory}
              </div>
            </div>
          )}

          {/* 7. CERT-In Portal Fields */}
          {certInEvidence.certInFields && (
            <div>
              {sectionLabel('7. CERT-In Portal Fields')}
              <p className="text-sm text-muted-foreground mb-4 uppercase tracking-wider">
                Copy and paste directly into the CERT-In online reporting portal
              </p>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-px bg-border">
                {[
                  { key: 'briefDescription',  label: 'Brief Description of Incident' },
                  { key: 'howDetected',        label: 'How Was the Incident Detected' },
                  { key: 'impact',             label: 'Impact of Incident' },
                  { key: 'actionsTaken',       label: 'Actions Taken' },
                ].map(({ key, label }) => (
                  <div key={key} className="bg-background p-6 group relative hover:border-l-4 hover:border-l-accent transition-all duration-200">
                    <div className="flex justify-between items-start mb-3 gap-3">
                      <p className="text-xs tracking-widest uppercase text-accent font-bold">{label}</p>
                      <CopyButton text={certInEvidence.certInFields[key] || ''} label={label.split(' ').slice(0, 2).join(' ')} />
                    </div>
                    <p className="text-sm text-foreground leading-relaxed">{certInEvidence.certInFields[key]}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Footer */}
          <div className="pt-6 border-t-2 border-border">
            <button
              onClick={copyAll}
              className="w-full border-2 border-border h-14 font-bold uppercase tracking-tighter text-lg text-foreground hover:bg-foreground hover:text-background transition-all duration-200 mb-4"
            >
              COPY ALL AS TEXT
            </button>
            <p className="text-sm text-muted-foreground text-center">
              ⚠️ Review and verify all details before CERT-In portal submission.
              CERTify is an analysis tool — human verification is mandatory before filing.
            </p>

            <button
              onClick={generateCERTInEvidenceAction}
              className="mt-4 w-full border-2 border-border h-10 text-xs font-bold uppercase tracking-widest text-muted-foreground hover:text-foreground transition-all duration-200"
            >
              REGENERATE EVIDENCE
            </button>
          </div>
        </div>
      )}
    </div>
  )
}
